import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const poppins = Poppins({ subsets: ["latin"], weight: ['400', '500', '600', '800', '700', '900'] });

export const metadata: Metadata = {
  title: {
    default: "Lay's",
    template: '%s - Smile with us'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-bg text-text`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
